version: '3.8'

services:
  db:
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: password
      POSTGRES_DB: living-pokedex
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/tmp/postgres/data

# Uncomment the following section if you are not running app from your IDE
#  app:
#    build: .
#    container_name: pokedex-app
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/pokedex

