version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: living-pokedex-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: living-pokedex

  app:
    build: .
    container_name: pokedex-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/pokedex

volumes:
  mongo_data: